[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["xpp"]

[tool.poetry.dependencies]
python = "^3.6"
sanic = "^19.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
